//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geolygon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class polygons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public polygons()
        {
            this.vertices = new HashSet<vertices>();
        }
    
        public int id { get; set; }
        public int properties_id { get; set; }
        public string identifier { get; set; }
        public string latitud { get; set; }
        public string longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vertices> vertices { get; set; }
        public virtual properties properties { get; set; }
    }
}
