//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geolygon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vertices
    {
        public int polygon_id { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    
        public virtual polygons polygons { get; set; }
    }
}
